git config --global alias.a "add"
git config --global alias.co "checkout"
git config --global alias.cob "checkout -B"
git config --global alias.d "diff"
git config --global alias.s "status -s"
git config --global alias.f "fetch"
git config --global alias.b "branch"
